name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Hämta repo
        uses: actions/checkout@v4

      - name: Bygg och deploya
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages 
          folder: . 
